export const visibleDocuments = {
  commercialRegistrations: [
    "ohg",
    "kg",
    "kgaa",
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "stiftung",
    "eingetragener_verein",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
    "other"
  ], // Handelsregisterauszug
  registerDocuments: ["e_k", "gbr", "kg","other"], // Gewerbeanmeldung
  statutes: [
    "gbr",
    "ohg",
    "kg",
    "kgaa",
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "stiftung",
    "eingetragener_verein",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
    "other"
  ], // Satzung
  shareholderDocs: [
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
    "other"
  ], // Gesellschafterliste
};

export const requiredDocuments = {
  commercialRegistrations: [
    "ohg",
    "kgaa",
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
  ], // Handelsregisterauszug
  registerDocuments: ["gbr", "kg"], // Gewerbeanmeldung
  statutes: [
    "ohg",
    "kgaa",
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "stiftung",
    "eingetragener_verein",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
  ], // Satzung
  shareholderDocs: [
    "gmbh_ug_haftungsbeschraenkt",
    "ag",
    "se",
    "gmbh_ug_haftungsbeschraenkt_co_kg",
    "gmbh_ug_haftungsbeschraenkt_co_ohg",
    "gmbh_ug_haftungsbeschraenkt_co_kgaa",
    "ag_co_kg",
    "ag_co_ohg",
    "ag_co_kgaa",
    "se_co_kg",
    "se_co_ohg",
    "se_co_kgaa",
    "ggmbh_gug_haftungsbeschraenkt",
    "gag",
  ], // Gesellschafterliste
};